### Footstep parameterization for the Aldebaran Robotics Nao humanoid ##########

### footstep settings ##########################################################
# Footstep displacement vectors (in meter / rad)
# WARNING: data type has to be float since integers will cause an exception
footsteps:
  x:     [0.000,0.040,0.026,0.040,0.026,-0.014,0.000,-0.014,-0.040,-0.054,-0.040,-0.054,0.000,0.030]
  y:     [0.095,0.095,0.093,0.135,0.133, 0.093,0.135, 0.133, 0.095, 0.093, 0.135, 0.133,0.088,0.088]
  theta: [0.000,0.000,0.300,0.000,0.300, 0.300,0.000, 0.300, 0.000, 0.300, 0.000, 0.300,0.000,0.000]


### foot settings ##############################################################
foot:
  size: {x: 0.16, y: 0.088, z: 0.015}
  separation: 0.095
  origin_shift: {x: 0.02, y: 0.006}
  max:
    step: {x: 0.06, y: 0.14, theta: 0.3}
    inverse:
      step: {x: -0.04, y: 0.088, theta: 0.0}
