"""autogenerated by genpy from flor_footstep_planner_msgs/PlanFootstepsRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import flor_footstep_planner_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class PlanFootstepsRequest(genpy.Message):
  _md5sum = "73c653370adcd272c83e55adc8dd672b"
  _type = "flor_footstep_planner_msgs/PlanFootstepsRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
uint8 planning_mode


uint8 start_type
uint8 goal_type

uint8 AREA = 0
uint8 POSE = 1
uint8 FEET = 2

geometry_msgs/Pose start
flor_footstep_planner_msgs/FeetPoses feet_start_poses

geometry_msgs/Pose goal
flor_footstep_planner_msgs/FeetPoses feet_goal_poses

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: flor_footstep_planner_msgs/FeetPoses
std_msgs/Header header
#flor_atlas_msgs/AtlasBehaviorFootData left
#flor_atlas_msgs/AtlasBehaviorFootData right

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  # Pseudo-constants
  AREA = 0
  POSE = 1
  FEET = 2

  __slots__ = ['planning_mode','start_type','goal_type','start','feet_start_poses','goal','feet_goal_poses']
  _slot_types = ['uint8','uint8','uint8','geometry_msgs/Pose','flor_footstep_planner_msgs/FeetPoses','geometry_msgs/Pose','flor_footstep_planner_msgs/FeetPoses']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       planning_mode,start_type,goal_type,start,feet_start_poses,goal,feet_goal_poses

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanFootstepsRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.planning_mode is None:
        self.planning_mode = 0
      if self.start_type is None:
        self.start_type = 0
      if self.goal_type is None:
        self.goal_type = 0
      if self.start is None:
        self.start = geometry_msgs.msg.Pose()
      if self.feet_start_poses is None:
        self.feet_start_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      if self.goal is None:
        self.goal = geometry_msgs.msg.Pose()
      if self.feet_goal_poses is None:
        self.feet_goal_poses = flor_footstep_planner_msgs.msg.FeetPoses()
    else:
      self.planning_mode = 0
      self.start_type = 0
      self.goal_type = 0
      self.start = geometry_msgs.msg.Pose()
      self.feet_start_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      self.goal = geometry_msgs.msg.Pose()
      self.feet_goal_poses = flor_footstep_planner_msgs.msg.FeetPoses()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B7d3I.pack(_x.planning_mode, _x.start_type, _x.goal_type, _x.start.position.x, _x.start.position.y, _x.start.position.z, _x.start.orientation.x, _x.start.orientation.y, _x.start.orientation.z, _x.start.orientation.w, _x.feet_start_poses.header.seq, _x.feet_start_poses.header.stamp.secs, _x.feet_start_poses.header.stamp.nsecs))
      _x = self.feet_start_poses.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.goal.position.x, _x.goal.position.y, _x.goal.position.z, _x.goal.orientation.x, _x.goal.orientation.y, _x.goal.orientation.z, _x.goal.orientation.w, _x.feet_goal_poses.header.seq, _x.feet_goal_poses.header.stamp.secs, _x.feet_goal_poses.header.stamp.nsecs))
      _x = self.feet_goal_poses.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.start is None:
        self.start = geometry_msgs.msg.Pose()
      if self.feet_start_poses is None:
        self.feet_start_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      if self.goal is None:
        self.goal = geometry_msgs.msg.Pose()
      if self.feet_goal_poses is None:
        self.feet_goal_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      end = 0
      _x = self
      start = end
      end += 71
      (_x.planning_mode, _x.start_type, _x.goal_type, _x.start.position.x, _x.start.position.y, _x.start.position.z, _x.start.orientation.x, _x.start.orientation.y, _x.start.orientation.z, _x.start.orientation.w, _x.feet_start_poses.header.seq, _x.feet_start_poses.header.stamp.secs, _x.feet_start_poses.header.stamp.nsecs,) = _struct_3B7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feet_start_poses.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.feet_start_poses.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.goal.position.x, _x.goal.position.y, _x.goal.position.z, _x.goal.orientation.x, _x.goal.orientation.y, _x.goal.orientation.z, _x.goal.orientation.w, _x.feet_goal_poses.header.seq, _x.feet_goal_poses.header.stamp.secs, _x.feet_goal_poses.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feet_goal_poses.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.feet_goal_poses.header.frame_id = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B7d3I.pack(_x.planning_mode, _x.start_type, _x.goal_type, _x.start.position.x, _x.start.position.y, _x.start.position.z, _x.start.orientation.x, _x.start.orientation.y, _x.start.orientation.z, _x.start.orientation.w, _x.feet_start_poses.header.seq, _x.feet_start_poses.header.stamp.secs, _x.feet_start_poses.header.stamp.nsecs))
      _x = self.feet_start_poses.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.goal.position.x, _x.goal.position.y, _x.goal.position.z, _x.goal.orientation.x, _x.goal.orientation.y, _x.goal.orientation.z, _x.goal.orientation.w, _x.feet_goal_poses.header.seq, _x.feet_goal_poses.header.stamp.secs, _x.feet_goal_poses.header.stamp.nsecs))
      _x = self.feet_goal_poses.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.start is None:
        self.start = geometry_msgs.msg.Pose()
      if self.feet_start_poses is None:
        self.feet_start_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      if self.goal is None:
        self.goal = geometry_msgs.msg.Pose()
      if self.feet_goal_poses is None:
        self.feet_goal_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      end = 0
      _x = self
      start = end
      end += 71
      (_x.planning_mode, _x.start_type, _x.goal_type, _x.start.position.x, _x.start.position.y, _x.start.position.z, _x.start.orientation.x, _x.start.orientation.y, _x.start.orientation.z, _x.start.orientation.w, _x.feet_start_poses.header.seq, _x.feet_start_poses.header.stamp.secs, _x.feet_start_poses.header.stamp.nsecs,) = _struct_3B7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feet_start_poses.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.feet_start_poses.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.goal.position.x, _x.goal.position.y, _x.goal.position.z, _x.goal.orientation.x, _x.goal.orientation.y, _x.goal.orientation.z, _x.goal.orientation.w, _x.feet_goal_poses.header.seq, _x.feet_goal_poses.header.stamp.secs, _x.feet_goal_poses.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feet_goal_poses.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.feet_goal_poses.header.frame_id = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B7d3I = struct.Struct("<3B7d3I")
_struct_7d3I = struct.Struct("<7d3I")
"""autogenerated by genpy from flor_footstep_planner_msgs/PlanFootstepsResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import flor_footstep_planner_msgs.msg
import std_msgs.msg

class PlanFootstepsResponse(genpy.Message):
  _md5sum = "8f5652575567e3c8e73f704b429057d3"
  _type = "flor_footstep_planner_msgs/PlanFootstepsResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool result
uint32 status_flags
flor_footstep_planner_msgs/FootstepPlan footstep_plan
flor_footstep_planner_msgs/FeetPoses feet_start_poses
float64 costs
float64 final_eps
float64 planning_time
int64 expanded_states


uint32 NONE                        =   0
uint32 GOAL_POSE_INACCESSIBLE      =   1
uint32 START_POSE_INACCESSIBLE     =   2
uint32 NO_BODY_LEVEL_GRID_MAP      =   4
uint32 NO_GROUND_LEVEL_GRID_MAP    =   8
uint32 NO_TERRAIN_MODEL            =  16
uint32 PLAN_SUBOPTIMAL             =  32
uint32 LARGE_HEIGHT_DIFF           =  64
uint32 MISC                        = 128


================================================================================
MSG: flor_footstep_planner_msgs/FootstepPlan
std_msgs/Header header
uint8 planning_mode                                         # (see below)

uint8 MODE_WALK                   = 0                       # simple planning for flat ground (default)
uint8 MODE_STEP                   = 1                       # finer planning of each step
uint8 MODE_FEET_REALIGN_ON_CENTER = 2                       # realign feet relative to robot pose
uint8 MODE_FEET_REALIGN_ON_LEFT   = 3                       # realign feet relative to left foot
uint8 MODE_FEET_REALIGN_ON_RIGHT  = 4                       # realign feet relative to right foot
uint8 MODE_WIDE_STANCE            = 5                       # special mode for wide stance

flor_footstep_planner_msgs/StepTarget[] step_plan           # resulting general footstep plan

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: flor_footstep_planner_msgs/StepTarget
# Target for a single stepping motion of a humanoid's leg
std_msgs/Header header
int32 step_index                            # Step index
uint8 foot_index                            # which leg to use (LEFT_FOOT/RIGHT_FOOT)
#flor_atlas_msgs/AtlasBehaviorFootData foot  # Foothold to step to
float32 step_duration                       # duration of the single support phase
float32 sway_duration                       # duration of the double support phase (optional)
float32 swing_height                        # step apex above the lift height while swinging the leg
float32 lift_height                         # height to lift vertically before moving the foot (optional)
int32 toe_off                               # specify whether toe-off is allowed or not during swaying
float32 knee_nominal                        # Nominal knee angle during the step. (optional)
float32 max_body_accel                      # Maximum body acceleration to determine minimum sway duration (optional)
float32 max_foot_vel                        # Maximum foot velocity to determine minimum step duration (optional)
float32 sway_end_dist                       # Distance short of the foot to aim for at the end of sway (in meters) (optional)
float32 step_end_dist                       # Distance to lean into the step before the foot comes down (in meters) (optional)

================================================================================
MSG: flor_footstep_planner_msgs/FeetPoses
std_msgs/Header header
#flor_atlas_msgs/AtlasBehaviorFootData left
#flor_atlas_msgs/AtlasBehaviorFootData right

"""
  # Pseudo-constants
  NONE = 0
  GOAL_POSE_INACCESSIBLE = 1
  START_POSE_INACCESSIBLE = 2
  NO_BODY_LEVEL_GRID_MAP = 4
  NO_GROUND_LEVEL_GRID_MAP = 8
  NO_TERRAIN_MODEL = 16
  PLAN_SUBOPTIMAL = 32
  LARGE_HEIGHT_DIFF = 64
  MISC = 128

  __slots__ = ['result','status_flags','footstep_plan','feet_start_poses','costs','final_eps','planning_time','expanded_states']
  _slot_types = ['bool','uint32','flor_footstep_planner_msgs/FootstepPlan','flor_footstep_planner_msgs/FeetPoses','float64','float64','float64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       result,status_flags,footstep_plan,feet_start_poses,costs,final_eps,planning_time,expanded_states

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanFootstepsResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.result is None:
        self.result = False
      if self.status_flags is None:
        self.status_flags = 0
      if self.footstep_plan is None:
        self.footstep_plan = flor_footstep_planner_msgs.msg.FootstepPlan()
      if self.feet_start_poses is None:
        self.feet_start_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      if self.costs is None:
        self.costs = 0.
      if self.final_eps is None:
        self.final_eps = 0.
      if self.planning_time is None:
        self.planning_time = 0.
      if self.expanded_states is None:
        self.expanded_states = 0
    else:
      self.result = False
      self.status_flags = 0
      self.footstep_plan = flor_footstep_planner_msgs.msg.FootstepPlan()
      self.feet_start_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      self.costs = 0.
      self.final_eps = 0.
      self.planning_time = 0.
      self.expanded_states = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B4I.pack(_x.result, _x.status_flags, _x.footstep_plan.header.seq, _x.footstep_plan.header.stamp.secs, _x.footstep_plan.header.stamp.nsecs))
      _x = self.footstep_plan.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.footstep_plan.planning_mode))
      length = len(self.footstep_plan.step_plan)
      buff.write(_struct_I.pack(length))
      for val1 in self.footstep_plan.step_plan:
        _v1 = val1.header
        buff.write(_struct_I.pack(_v1.seq))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_struct_2I.pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_iB4fi5f.pack(_x.step_index, _x.foot_index, _x.step_duration, _x.sway_duration, _x.swing_height, _x.lift_height, _x.toe_off, _x.knee_nominal, _x.max_body_accel, _x.max_foot_vel, _x.sway_end_dist, _x.step_end_dist))
      _x = self
      buff.write(_struct_3I.pack(_x.feet_start_poses.header.seq, _x.feet_start_poses.header.stamp.secs, _x.feet_start_poses.header.stamp.nsecs))
      _x = self.feet_start_poses.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3dq.pack(_x.costs, _x.final_eps, _x.planning_time, _x.expanded_states))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.footstep_plan is None:
        self.footstep_plan = flor_footstep_planner_msgs.msg.FootstepPlan()
      if self.feet_start_poses is None:
        self.feet_start_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.result, _x.status_flags, _x.footstep_plan.header.seq, _x.footstep_plan.header.stamp.secs, _x.footstep_plan.header.stamp.nsecs,) = _struct_B4I.unpack(str[start:end])
      self.result = bool(self.result)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.footstep_plan.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.footstep_plan.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.footstep_plan.planning_mode,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.footstep_plan.step_plan = []
      for i in range(0, length):
        val1 = flor_footstep_planner_msgs.msg.StepTarget()
        _v3 = val1.header
        start = end
        end += 4
        (_v3.seq,) = _struct_I.unpack(str[start:end])
        _v4 = _v3.stamp
        _x = _v4
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _struct_2I.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v3.frame_id = str[start:end].decode('utf-8')
        else:
          _v3.frame_id = str[start:end]
        _x = val1
        start = end
        end += 45
        (_x.step_index, _x.foot_index, _x.step_duration, _x.sway_duration, _x.swing_height, _x.lift_height, _x.toe_off, _x.knee_nominal, _x.max_body_accel, _x.max_foot_vel, _x.sway_end_dist, _x.step_end_dist,) = _struct_iB4fi5f.unpack(str[start:end])
        self.footstep_plan.step_plan.append(val1)
      _x = self
      start = end
      end += 12
      (_x.feet_start_poses.header.seq, _x.feet_start_poses.header.stamp.secs, _x.feet_start_poses.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feet_start_poses.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.feet_start_poses.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.costs, _x.final_eps, _x.planning_time, _x.expanded_states,) = _struct_3dq.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B4I.pack(_x.result, _x.status_flags, _x.footstep_plan.header.seq, _x.footstep_plan.header.stamp.secs, _x.footstep_plan.header.stamp.nsecs))
      _x = self.footstep_plan.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.footstep_plan.planning_mode))
      length = len(self.footstep_plan.step_plan)
      buff.write(_struct_I.pack(length))
      for val1 in self.footstep_plan.step_plan:
        _v5 = val1.header
        buff.write(_struct_I.pack(_v5.seq))
        _v6 = _v5.stamp
        _x = _v6
        buff.write(_struct_2I.pack(_x.secs, _x.nsecs))
        _x = _v5.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_iB4fi5f.pack(_x.step_index, _x.foot_index, _x.step_duration, _x.sway_duration, _x.swing_height, _x.lift_height, _x.toe_off, _x.knee_nominal, _x.max_body_accel, _x.max_foot_vel, _x.sway_end_dist, _x.step_end_dist))
      _x = self
      buff.write(_struct_3I.pack(_x.feet_start_poses.header.seq, _x.feet_start_poses.header.stamp.secs, _x.feet_start_poses.header.stamp.nsecs))
      _x = self.feet_start_poses.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3dq.pack(_x.costs, _x.final_eps, _x.planning_time, _x.expanded_states))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.footstep_plan is None:
        self.footstep_plan = flor_footstep_planner_msgs.msg.FootstepPlan()
      if self.feet_start_poses is None:
        self.feet_start_poses = flor_footstep_planner_msgs.msg.FeetPoses()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.result, _x.status_flags, _x.footstep_plan.header.seq, _x.footstep_plan.header.stamp.secs, _x.footstep_plan.header.stamp.nsecs,) = _struct_B4I.unpack(str[start:end])
      self.result = bool(self.result)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.footstep_plan.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.footstep_plan.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.footstep_plan.planning_mode,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.footstep_plan.step_plan = []
      for i in range(0, length):
        val1 = flor_footstep_planner_msgs.msg.StepTarget()
        _v7 = val1.header
        start = end
        end += 4
        (_v7.seq,) = _struct_I.unpack(str[start:end])
        _v8 = _v7.stamp
        _x = _v8
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _struct_2I.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v7.frame_id = str[start:end].decode('utf-8')
        else:
          _v7.frame_id = str[start:end]
        _x = val1
        start = end
        end += 45
        (_x.step_index, _x.foot_index, _x.step_duration, _x.sway_duration, _x.swing_height, _x.lift_height, _x.toe_off, _x.knee_nominal, _x.max_body_accel, _x.max_foot_vel, _x.sway_end_dist, _x.step_end_dist,) = _struct_iB4fi5f.unpack(str[start:end])
        self.footstep_plan.step_plan.append(val1)
      _x = self
      start = end
      end += 12
      (_x.feet_start_poses.header.seq, _x.feet_start_poses.header.stamp.secs, _x.feet_start_poses.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feet_start_poses.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.feet_start_poses.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.costs, _x.final_eps, _x.planning_time, _x.expanded_states,) = _struct_3dq.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_3dq = struct.Struct("<3dq")
_struct_3I = struct.Struct("<3I")
_struct_iB4fi5f = struct.Struct("<iB4fi5f")
_struct_B4I = struct.Struct("<B4I")
_struct_2I = struct.Struct("<2I")
class PlanFootsteps(object):
  _type          = 'flor_footstep_planner_msgs/PlanFootsteps'
  _md5sum = 'c422551db6c901f6034b77b0547e37d5'
  _request_class  = PlanFootstepsRequest
  _response_class = PlanFootstepsResponse
