flor_footstep_planner_msgs/SteppingRequest stepping_request
---
bool result                                                 # Indicates planning success (true) or failure (false)
uint32 status_flags                                         # status flags of planner (see PlanFootsteps.srv)
uint8 planning_mode                                         # selected planning mode (see FootstepPlan.msg)
flor_footstep_planner_msgs/AtlasWalkFootstepPlan walk_plan  # resulting plan in MODE_WALK
flor_footstep_planner_msgs/AtlasStepFootstepPlan step_plan  # resulting plan in MODE_STEP
flor_footstep_planner_msgs/FeetPoses feet_start_poses       # contains feet start poses used by planner
float64 costs
float64 final_eps
float64 planning_time
int64 expanded_states
