# Retrieve motion plan for joint configuration

# The plan request
flor_planning_msgs/PlanToJointTargetRequest plan_request
---
uint8       OK                = 0
uint8       OCTOMAP_WARNING   = 1
uint8       IK_FAILED         = 2
uint8       PLANNER_EXCEPTION = 4
uint8       PLANNING_FAILED   = 8

trajectory_msgs/JointTrajectory trajectory

uint8                           status

#Can be different from requested group
std_msgs/String                 used_planning_group
