# Retrieve motion plan for cartesian waypoints

CartesianMotionRequest plan_request
---

# The resulting trajectory
trajectory_msgs/JointTrajectory trajectory

# The fraction of the requested movement that could be performed (in range 0..1)
float32 successful_plan_fraction

uint8                           status